services:
  mongodb:
    image: "mongodb/mongodb-community-server"
    env_file: ".env"
    ports:
      - "${DATABASE_PORT}:27017"
  redis:
    image: "redis"
    env_file: ".env"
    ports:
      - "${REDIS_PORT}:6379"